AllCops:
  TargetRubyVersion: 2.5.1
Style/Documentation:
  Enabled: false
# Style/GuardClause:
#   Enabled: false
# Metrics/AbcSize:
#   Enabled: false
Metrics/BlockLength:
  Enabled: false
# Metrics/CyclomaticComplexity:
#   Enabled: false
# Metrics/ClassLength:
#   Max: 200
Metrics/ModuleLength:
    Max: 500
Metrics/LineLength:
  Max: 120
# Metrics/MethodLength:
#   Enabled: false
# Metrics/PerceivedComplexity:
#   Enabled: false
# Style/ClassAndModuleChildren:
#   EnforcedStyle: compact
